### ISSUE TITLE
Code with MIMIC-III data

### ISSUE THREAD

**Issue by zhangyongheng78** [vanderschaarlab/mlforhealthlabpub#11] opened 2021-08-09 04:10 UTC
Hi, thank you for providing the CartPole example in terms of using the AVRIL algorithm. 

I wonder could you also provide the code for testing MIMIC-III data using the AVRIL algorithm? I am curious in what way you generated "inputs,targets,a_dim,s_dim" just like the CartPole example usage. 

And also, in what way you merged different data frames and conducted a final version for training. I know the dataset is credential but I am really interested in the coding portion since I already got the dataset by application.

I believe your sharing will be beneficial for many of us! Thank you very much!

**Comment by zhangyongheng78** [comment] 2021-08-09 04:11
https://github.com/vanderschaarlab/mlforhealthlabpub/tree/main/alg/scalable-birl

Above is the repo that is related to the issue I raised. Thanks!

**Comment by DrShushen** [comment] 2022-02-13 15:27
Closing as is duplicate of https://github.com/XanderJC/scalable-birl/issues/5

**Closed by DrShushen** 2022-02-13 15:27 UTC
